version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/busticket
      SPRING_DATASOURCE_USERNAME: busticket
      SPRING_DATASOURCE_PASSWORD: busticket
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      spring.jpa.show-sql: true
      # Other environment variables your backend needs
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: busticket
      POSTGRES_USER: busticket
      POSTGRES_PASSWORD: busticket
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
